- id: doi.org/10.1371/journal.pmen.0000574
  topics:
    - intergenerational trauma
    - Mental Health
    - Family Studies
  keywords:
    - intergenerational trauma
    - Mental health and psychiatry
    - Depression
    - anxiety disorder
    - emotions
    - human families
    - suveys
    - Post-traumatic stress disorder
  featured: true
  preprint: false
  pdf:
  materials:
  code:
  
- id: doi.org/10.3390/ijerph21080988
  topics:
    - Trauma
    - Mental Health
    - Family Studies
  keywords:
    - comorbidity
    - trauma
    - children
    - 9/11
    - disaster
  featured: true
  preprint: false
  pdf:
  materials:
  code:

  - id: doi.org/10.3390/children11060671
  topics:
    - Trauma
    - Mental Health
    - Family Studies
  keywords:
    - family history
    - substance use disorder
    - minority cohort
    - family environment
  featured: true
  preprint: false
  pdf:
  materials:
  code:
